log_target = "stderr"
log_level = "info"

# jwt_secret is randomized when backend-setupcfg is ran
jwt_secret = "KrTidID0s8udOPENmXGCbZRieeYy5QR5yiEKKeZYTuNqTzQRqSNcj5DhY2kCAqgmViw8YsNFGP826vIY5kB0XvgYaGvnS3dpEi6mQmaEL1DoV4tSKNEiKNn1dqcxrBiu"
jwt_expiry_days = 7
google_client_id = "670389606214-ue7v08b9n22ok3v5bnjq59pvrlfcsk3a.apps.googleusercontent.com"
google_client_secret = "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"
google_callback_uri = "http://simplify.com:8080/google/callback"

[api]
host = "0.0.0.0"
port = 8080

[db]
# if using postgres over tcp:
host = "localhost"
port = 5432
# if using postgres over a domain socket:
# host = "/var/run/postgresql/"

user = "backend"
password = "yoursupersecretpassword"
dbname = "public"
current_migration = ""

[ollama]
endpoint = "http://localhost:11434/"
model = "mistral:7b-instruct-v0.2-q4_K_M"
