log_target = "stderr"
log_level = "info"

[auth]
# jwt_secret is randomized when backend-setupcfg is ran
jwt_secret = "secret_with_at_least_32_characters"
jwt_expiry_days = 7
bcrypt_rounds = 12
google_client_id = "yourapp.apps.googleusercontent.com"
google_client_secret = "superbigsecret"
google_callback_uri = "http://simplify.com:8080/google/callback"

[api]
host = "0.0.0.0"
port = 8080

[db]
## A postgres connection string to connect to, documented at:
## https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING
# If using postgres over tcp:
# conx = "host=localhost port=5432 dbname=public user=username password=yoursupersecretpassword"
# If using postgres over a domain socket:
conx = "host=/var/run/postgresql/ dbname=public"

current_migration = ""
pgrest_anon_role = "pgrest_anon"
pgrest_auth_role = "pgrest_auth"

[ollama]
endpoint = "http://localhost:11434/"
model = "mistral:7b-instruct-v0.2-q4_K_M"
