[project]
name = "backend"
version = "0.1.0"
description = "web summarizer for 4p02"
requires-python = ">=3.8"
# readme = "README.md"
# license = {file = "LICENSE"}

dependencies = [
    "fastapi~=0.109",
    "uvicorn~=0.27",
    "jwt~=1.3",
    "psycopg2~=2.8",
    "typeguard~=4.1",
    "ollama~=0.1",
]

[project.scripts]
backend = "backend:main"
backend-setupcfg = "backend.cli:setup_cfg"
