[project]
name = "backend"
version = "0.1.0"
description = "web summarizer for 4p02"

# 3.10 for match/case, 3.11 for tomllib builtin
requires-python = ">=3.11"

readme = "README.md"

dependencies = [
    "fastapi ~= 0.109",
    "uvicorn ~= 0.27",
    "jwt ~= 1.3",
    "typeguard ~= 4.1",
    "ollama ~= 0.1",
]

[build-system]
# setuptools 61 needed needed for tool.setuptools.package-data support
requires = ["setuptools ~= 61.0"]

[tool.setuptools.package-data]
backend = ["*.toml"]

[project.scripts]
backend = "backend.main:main"
backend-setupcfg = "backend.cli:setup_cfg"
backend-migrate = "backend.cli:migrate_db"
