

-- Not public
create table public.users (
    id bigint generated by default as identity primary key unique not null,
    created_at timestamp with time zone null default now(),
    email text unique not null,
    password text not null,
    fullname text not null
);


create type public.article_type as enum('webpage', 'video', 'document');

-- public
create table public.documents (
    id bigint generated by default as identity primary key unique not null,
    created_at timestamp with time zone null default now(),
    filename text,
    body bytea not null,
    source_url text default null,
    summary bytea default null
);



-- public
create table public.articles (
    id bigint generated by default as identity primary key unique not null,
    owner bigint not null references public.users(id),
    type article_type not null,
    history bigint[] not null references public.documents(id),
    private boolean not null
);
-- TODO: Add a trigger to delete the history when the article is deleted


-- public
create table public.links (
    given_link text not null,
    shortened_link unique text not null
);
